table 'Table (2)'
	lineageTag: ae776145-2e6e-4705-844b-53b2d644553b

	measure sum = SUM('Table (2)'[Column1])
		formatString: 0
		lineageTag: f5b29920-18ed-4dca-aebe-e1b588efa40e

	column Column1
		dataType: int64
		formatString: 0
		lineageTag: 762d94d6-a8a2-4aac-a84e-67cead0a3085
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition 'Table (2)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSK1YlWMgKTxkqxsQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

